# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pylint-dev/pylint
    rev: v3.2.6
    hooks:
    -   id: pylint